### ISSUE TITLE
RAILS_ENV is not when using capistrano 2 tasks

### ISSUE THREAD

**Issue by phoolish** [tablexi/eye-patch#11]

**Comment by soulcutter** [comment]
Can you elaborate? I think that's only in examples…

**Comment by phoolish** [comment]
https://github.com/tablexi/eye-patch/blob/master/lib/eye/patch/capistrano.rb Doesn't have a reference to eye_env variable. Which is used in cap 3 to set RAILS_ENV on most of our projects

**Comment by phoolish** [comment]
I don't think any of our projects use cap 2 anymore.
